import { QuestionTemplate } from './questionUtils';

const REAL_ASSESS: Record<string, QuestionTemplate[]> = {
    "101": [
        { q: "Do plants drink water?", options: ["Yes", "No"], correctIndex: 0, hint: "Thirsty.", explanation: "Yes." },
        { q: "Where do roots grow?", options: ["Underground", "In sky", "On leaves", "In water"], correctIndex: 0, hint: "Dirt.", explanation: "Underground." },
        { q: "Leaves are usually?", options: ["Green", "Blue", "Black", "White"], correctIndex: 0, hint: "Grass color.", explanation: "Green." },
        { q: "Sunlight helps plants?", options: ["Grow", "Sleep", "Run", "Cry"], correctIndex: 0, hint: "Big.", explanation: "Grow." },
        { q: "Is a dog a plant?", options: ["No", "Yes"], correctIndex: 0, hint: "Animal.", explanation: "No." },
        { q: "Seeds turn into?", options: ["Plants", "Rocks", "Cars", "Toys"], correctIndex: 0, hint: "Grow.", explanation: "Plants." },
        { q: "Flower petal color?", options: ["Any color", "Invisible", "Clear", "None"], correctIndex: 0, hint: "Colorful.", explanation: "Any color." },
        { q: "Do plants eat pizza?", options: ["No", "Yes"], correctIndex: 0, hint: "Sunlight.", explanation: "No." },
        { q: "What is a baby plant?", options: ["Sprout", "Puppy", "Kitten", "Cub"], correctIndex: 0, hint: "Small.", explanation: "Sprout." },
        { q: "Tree trunk is?", options: ["Hard", "Soft", "Liquid", "Gas"], correctIndex: 0, hint: "Wood.", explanation: "Hard." },
        { q: "Plants need air?", options: ["Yes", "No"], correctIndex: 0, hint: "Breathe.", explanation: "Yes." },
        { q: "Where is the stem?", options: ["Middle", "Bottom", "Top", "Nowhere"], correctIndex: 0, hint: "Holds up.", explanation: "Middle." },
        { q: "Fruit comes from?", options: ["Plants", "Sky", "Rocks", "Ocean"], correctIndex: 0, hint: "Trees.", explanation: "Plants." },
        { q: "Is a rock alive?", options: ["No", "Yes"], correctIndex: 0, hint: "Stone.", explanation: "No." },
        { q: "Grass is a?", options: ["Plant", "Animal", "Mineral", "Gas"], correctIndex: 0, hint: "Green.", explanation: "Plant." }
    ],
    "102": [
        { q: "Senses count?", options: ["5", "10", "2", "1"], correctIndex: 0, hint: "Hand.", explanation: "5." },
        { q: "Eyes are for?", options: ["Seeing", "Hearing", "Tasting", "Smelling"], correctIndex: 0, hint: "Look.", explanation: "Seeing." },
        { q: "Ears are for?", options: ["Hearing", "Seeing", "Touching", "Tasting"], correctIndex: 0, hint: "Listen.", explanation: "Hearing." },
        { q: "Nose is for?", options: ["Smelling", "Seeing", "Hearing", "Walking"], correctIndex: 0, hint: "Scent.", explanation: "Smelling." },
        { q: "Skin is for?", options: ["Touching", "Tasting", "Seeing", "Hearing"], correctIndex: 0, hint: "Feel.", explanation: "Touching." },
        { q: "Tongue is for?", options: ["Tasting", "Seeing", "Hearing", "Smelling"], correctIndex: 0, hint: "Food.", explanation: "Tasting." },
        { q: "Hands are for?", options: ["Touching", "Smelling", "Tasting", "Hearing"], correctIndex: 0, hint: "Feel.", explanation: "Touching." },
        { q: "Can you smell a flower?", options: ["Yes", "No"], correctIndex: 0, hint: "Nose.", explanation: "Yes." },
        { q: "Can you taste a sound?", options: ["No", "Yes"], correctIndex: 0, hint: "Ear.", explanation: "No." },
        { q: "Do glasses help see?", options: ["Yes", "No"], correctIndex: 0, hint: "Eyes.", explanation: "Yes." },
        { q: "Is ice cold?", options: ["Yes", "No"], correctIndex: 0, hint: "Touch.", explanation: "Yes." },
        { q: "Is fire hot?", options: ["Yes", "No"], correctIndex: 0, hint: "Touch.", explanation: "Yes." },
        { q: "Can you hear a whisper?", options: ["Yes", "No"], correctIndex: 0, hint: "Ear.", explanation: "Yes." },
        { q: "Is a lemon sour?", options: ["Yes", "No"], correctIndex: 0, hint: "Taste.", explanation: "Yes." },
        { q: "Is a rainbow colorful?", options: ["Yes", "No"], correctIndex: 0, hint: "Sight.", explanation: "Yes." }
    ],
    "103": [
        { q: "Sun creates?", options: ["Day", "Night", "Rain", "Snow"], correctIndex: 0, hint: "Light.", explanation: "Day." },
        { q: "Cloudy means?", options: ["No sun seen", "Bright sun", "Starry", "Clear"], correctIndex: 0, hint: "Grey.", explanation: "No sun seen." },
        { q: "Rain falls from?", options: ["Clouds", "Sun", "Moon", "Ground"], correctIndex: 0, hint: "Sky.", explanation: "Clouds." },
        { q: "Snow is?", options: ["Cold", "Hot", "Warm", "Dry"], correctIndex: 0, hint: "Ice.", explanation: "Cold." },
        { q: "Wind is?", options: ["Moving air", "Still air", "Water", "Fire"], correctIndex: 0, hint: "Blow.", explanation: "Moving air." },
        { q: "Thunder sound?", options: ["Boom", "Beep", "Meow", "Shh"], correctIndex: 0, hint: "Loud.", explanation: "Boom." },
        { q: "Lightning is?", options: ["Bright flash", "Water", "Wind", "Snow"], correctIndex: 0, hint: "Electricity.", explanation: "Bright flash." },
        { q: "Umbrella for?", options: ["Rain", "Snow", "Wind", "Sun"], correctIndex: 0, hint: "Dry.", explanation: "Rain." },
        { q: "Puddle comes from?", options: ["Rain", "Wind", "Sun", "Cloud"], correctIndex: 0, hint: "Water.", explanation: "Rain." },
        { q: "Rainbow comes after?", options: ["Rain", "Snow", "Wind", "Night"], correctIndex: 0, hint: "Sun + Rain.", explanation: "Rain." },
        { q: "Sunglasses for?", options: ["Sun", "Rain", "Snow", "Night"], correctIndex: 0, hint: "Bright.", explanation: "Sun." },
        { q: "Can wind blow trees?", options: ["Yes", "No"], correctIndex: 0, hint: "Force.", explanation: "Yes." },
        { q: "Is fog like a cloud?", options: ["Yes", "No"], correctIndex: 0, hint: "Low.", explanation: "Yes." },
        { q: "Does snow melt?", options: ["Yes", "No"], correctIndex: 0, hint: "Water.", explanation: "Yes." },
        { q: "Is the sun hot?", options: ["Yes", "No"], correctIndex: 0, hint: "Heat.", explanation: "Yes." }
    ],
    "104": [
        { q: "Season with snow?", options: ["Winter", "Summer", "Spring", "Fall"], correctIndex: 0, hint: "Cold.", explanation: "Winter." },
        { q: "Season with flowers?", options: ["Spring", "Winter", "Fall", "Summer"], correctIndex: 0, hint: "Grow.", explanation: "Spring." },
        { q: "Hot season?", options: ["Summer", "Winter", "Spring", "Fall"], correctIndex: 0, hint: "Sun.", explanation: "Summer." },
        { q: "Leaves fall in?", options: ["Autumn", "Winter", "Spring", "Summer"], correctIndex: 0, hint: "Fall.", explanation: "Autumn." },
        { q: "Wear coat in?", options: ["Winter", "Summer", "Spring", "June"], correctIndex: 0, hint: "Cold.", explanation: "Winter." },
        { q: "Swim in?", options: ["Summer", "Winter", "Fall", "Spring"], correctIndex: 0, hint: "Hot.", explanation: "Summer." },
        { q: "Build snowman in?", options: ["Winter", "Summer", "Spring", "Fall"], correctIndex: 0, hint: "Snow.", explanation: "Winter." },
        { q: "Baby animals born in?", options: ["Spring", "Winter", "Fall", "Summer"], correctIndex: 0, hint: "New life.", explanation: "Spring." },
        { q: "Pumpkins in?", options: ["Fall", "Spring", "Summer", "Winter"], correctIndex: 0, hint: "Halloween.", explanation: "Fall." },
        { q: "Sun hottest in?", options: ["Summer", "Winter", "Spring", "Fall"], correctIndex: 0, hint: "Heat.", explanation: "Summer." },
        { q: "How many seasons?", options: ["4", "2", "12", "1"], correctIndex: 0, hint: "Count.", explanation: "4." },
        { q: "Is July in winter?", options: ["No", "Yes"], correctIndex: 0, hint: "Summer.", explanation: "No." },
        { q: "Is December in winter?", options: ["Yes", "No"], correctIndex: 0, hint: "Cold.", explanation: "Yes." },
        { q: "Do bears sleep in winter?", options: ["Yes", "No"], correctIndex: 0, hint: "Hibernate.", explanation: "Yes." },
        { q: "Do birds fly south?", options: ["Yes", "No"], correctIndex: 0, hint: "Winter.", explanation: "Yes." }
    ],
    "201": [
        { q: "Loud sound?", options: ["Drum", "Feather", "Whisper", "Sleep"], correctIndex: 0, hint: "Bang.", explanation: "Drum." },
        { q: "Soft sound?", options: ["Whisper", "Scream", "Horn", "Boom"], correctIndex: 0, hint: "Quiet.", explanation: "Whisper." },
        { q: "Sound travels to?", options: ["Ears", "Eyes", "Nose", "Toes"], correctIndex: 0, hint: "Hear.", explanation: "Ears." },
        { q: "Vibration means?", options: ["Shaking fast", "Sleeping", "Eating", "Running"], correctIndex: 0, hint: "Buzz.", explanation: "Shaking fast." },
        { q: "Can sound move water?", options: ["Yes", "No"], correctIndex: 0, hint: "Ripples.", explanation: "Yes." },
        { q: "No sound is called?", options: ["Silence", "Loud", "Noise", "Music"], correctIndex: 0, hint: "Quiet.", explanation: "Silence." },
        { q: "Guitar makes sound with?", options: ["Strings", "Keys", "Drum", "Air"], correctIndex: 0, hint: "Pluck.", explanation: "Strings." },
        { q: "Flute uses?", options: ["Air", "Strings", "Hit", "Shake"], correctIndex: 0, hint: "Blow.", explanation: "Air." },
        { q: "High pitch?", options: ["Whistle", "Thunder", "Lion", "Bear"], correctIndex: 0, hint: "Squeak.", explanation: "Whistle." },
        { q: "Low pitch?", options: ["Thunder", "Bird", "Bell", "Mouse"], correctIndex: 0, hint: "Boom.", explanation: "Thunder." },
        { q: "Echolocation used by?", options: ["Bat", "Dog", "Cat", "Fish"], correctIndex: 0, hint: "Night flyer.", explanation: "Bat." },
        { q: "Sound wave?", options: ["Invisible", "Blue", "Red", "Square"], correctIndex: 0, hint: "Cant see.", explanation: "Invisible." },
        { q: "Protect ears from?", options: ["Loud noise", "Soft music", "Whispers", "Silence"], correctIndex: 0, hint: "Ouch.", explanation: "Loud noise." },
        { q: "Phone rings with?", options: ["Sound", "Smell", "Taste", "Touch"], correctIndex: 0, hint: "Ring.", explanation: "Sound." },
        { q: "Echo is?", options: ["Bouncing sound", "New sound", "Quiet", "Gone"], correctIndex: 0, hint: "Repeat.", explanation: "Bouncing sound." }
    ],
    "202": [
        { q: "Shadow needs?", options: ["Light & Object", "Darkness"], correctIndex: 0, hint: "Block.", explanation: "Light & Object." },
        { q: "Transparent?", options: ["See through", "Solid"], correctIndex: 0, hint: "Clear.", explanation: "See through." },
        { q: "Opaque?", options: ["Blocks light", "Clear"], correctIndex: 0, hint: "Solid.", explanation: "Blocks light." },
        { q: "Reflection?", options: ["Mirror", "Wall", "Carpet", "Dog"], correctIndex: 0, hint: "Bounce.", explanation: "Mirror." },
        { q: "Sun gives?", options: ["Light", "Dark"], correctIndex: 0, hint: "Bright.", explanation: "Light." },
        { q: "Moon reflects?", options: ["Sunlight", "Water", "Fire", "Earth"], correctIndex: 0, hint: "Shine.", explanation: "Sunlight." },
        { q: "Glass is?", options: ["Transparent", "Opaque", "Solid", "Gas"], correctIndex: 0, hint: "Clear.", explanation: "Transparent." },
        { q: "Wall is?", options: ["Opaque", "Transparent", "Liquid", "Gas"], correctIndex: 0, hint: "Block.", explanation: "Opaque." },
        { q: "Shadow gets long when?", options: ["Sun is low", "Sun is high", "Night", "Cloudy"], correctIndex: 0, hint: "Sunset.", explanation: "Sun is low." },
        { q: "No light means?", options: ["Darkness", "Bright", "Day", "Color"], correctIndex: 0, hint: "Black.", explanation: "Darkness." },
        { q: "Rainbow has?", options: ["Colors", "Black", "White", "Grey"], correctIndex: 0, hint: "ROYGBIV.", explanation: "Colors." },
        { q: "Flashlight makes?", options: ["Beam", "Darkness", "Sound", "Wind"], correctIndex: 0, hint: "Light.", explanation: "Beam." },
        { q: "Can light bend?", options: ["Yes (Refract)", "No", "Never", "Only water"], correctIndex: 0, hint: "Glass.", explanation: "Yes (Refract)." },
        { q: "Is fire a light source?", options: ["Yes", "No"], correctIndex: 0, hint: "Flame.", explanation: "Yes." },
        { q: "Is a rock a light source?", options: ["No", "Yes"], correctIndex: 0, hint: "Stone.", explanation: "No." }
    ],
    "203": [
        { q: "Baby dog?", options: ["Puppy", "Kitten", "Cub", "Chick"], correctIndex: 0, hint: "Woof.", explanation: "Puppy." },
        { q: "Baby cat?", options: ["Kitten", "Puppy", "Calf", "Foal"], correctIndex: 0, hint: "Meow.", explanation: "Kitten." },
        { q: "Does baby look like parent?", options: ["Yes", "No", "Maybe", "Never"], correctIndex: 0, hint: "Similar.", explanation: "Yes." },
        { q: "Frog baby?", options: ["Tadpole", "Fish", "Worm", "Fly"], correctIndex: 0, hint: "Swim.", explanation: "Tadpole." },
        { q: "Bird lays?", options: ["Eggs", "Seeds", "Rocks", "Milk"], correctIndex: 0, hint: "Nest.", explanation: "Eggs." },
        { q: "Baby cow?", options: ["Calf", "Foal", "Kid", "Lamb"], correctIndex: 0, hint: "Moo.", explanation: "Calf." },
        { q: "Baby horse?", options: ["Foal", "Calf", "Kid", "Lamb"], correctIndex: 0, hint: "Neigh.", explanation: "Foal." },
        { q: "Baby chicken?", options: ["Chick", "Duckling", "Gosling", "Puppy"], correctIndex: 0, hint: "Peep.", explanation: "Chick." },
        { q: "Do parents feed babies?", options: ["Yes", "No"], correctIndex: 0, hint: "Hungry.", explanation: "Yes." },
        { q: "Does a seed have a baby plant?", options: ["Yes", "No"], correctIndex: 0, hint: "Grow.", explanation: "Yes." },
        { q: "Baby bear?", options: ["Cub", "Pup", "Kit", "Kid"], correctIndex: 0, hint: "Growl.", explanation: "Cub." },
        { q: "Baby sheep?", options: ["Lamb", "Kid", "Calf", "Foal"], correctIndex: 0, hint: "Baa.", explanation: "Lamb." },
        { q: "Baby goat?", options: ["Kid", "Lamb", "Calf", "Cub"], correctIndex: 0, hint: "Billy.", explanation: "Kid." },
        { q: "Baby duck?", options: ["Duckling", "Chick", "Gosling", "Cygnet"], correctIndex: 0, hint: "Quack.", explanation: "Duckling." },
        { q: "Baby lion?", options: ["Cub", "Kitten", "Pup", "Joey"], correctIndex: 0, hint: "Roar.", explanation: "Cub." }
    ],
    "204": [
        { q: "Roots job?", options: ["Drink water", "Make seeds", "Look pretty", "Fly"], correctIndex: 0, hint: "Straw.", explanation: "Drink water." },
        { q: "Stem job?", options: ["Hold up plant", "Eat", "Sleep", "Run"], correctIndex: 0, hint: "Support.", explanation: "Hold up plant." },
        { q: "Leaf job?", options: ["Make food", "Drink", "Walk", "Talk"], correctIndex: 0, hint: "Sun.", explanation: "Make food." },
        { q: "Flower job?", options: ["Seeds", "Leaves", "Roots", "Dirt"], correctIndex: 0, hint: "Baby.", explanation: "Seeds." },
        { q: "Fruit has?", options: ["Seeds", "Roots", "Dirt", "Leaves"], correctIndex: 0, hint: "Inside.", explanation: "Seeds." },
        { q: "Pollen helps?", options: ["Make seeds", "Drink water", "Hold plant", "Grow leaves"], correctIndex: 0, hint: "Bees.", explanation: "Make seeds." },
        { q: "Do leaves need sun?", options: ["Yes", "No"], correctIndex: 0, hint: "Food.", explanation: "Yes." },
        { q: "Do roots need light?", options: ["No", "Yes"], correctIndex: 0, hint: "Underground.", explanation: "No." },
        { q: "Is a carrot a root?", options: ["Yes", "No"], correctIndex: 0, hint: "Orange.", explanation: "Yes." },
        { q: "Is celery a stem?", options: ["Yes", "No"], correctIndex: 0, hint: "Stalk.", explanation: "Yes." },
        { q: "Is lettuce a leaf?", options: ["Yes", "No"], correctIndex: 0, hint: "Salad.", explanation: "Yes." },
        { q: "Is apple a fruit?", options: ["Yes", "No"], correctIndex: 0, hint: "Seeds.", explanation: "Yes." },
        { q: "Do plants need soil?", options: ["Usually Yes", "Never", "No"], correctIndex: 0, hint: "Nutrients.", explanation: "Usually Yes." },
        { q: "Do plants need air?", options: ["Yes", "No"], correctIndex: 0, hint: "Breathe.", explanation: "Yes." },
        { q: "Can plants move?", options: ["Grow towards light", "Walk", "Run", "Jump"], correctIndex: 0, hint: "Sun.", explanation: "Grow towards light." }
    ],
    "301": [
        { q: "Liquid?", options: ["Milk", "Ice", "Wood", "Stone"], correctIndex: 0, hint: "Pour.", explanation: "Milk." },
        { q: "Gas?", options: ["Air", "Water", "Ice", "Dirt"], correctIndex: 0, hint: "Breathe.", explanation: "Air." },
        { q: "Solid shape?", options: ["Stays same", "Changes", "Flows", "Fills room"], correctIndex: 0, hint: "Rigid.", explanation: "Stays same." },
        { q: "Liquid shape?", options: ["Fills container", "Stays same", "Hard", "Fixed"], correctIndex: 0, hint: "Cup.", explanation: "Fills container." },
        { q: "Ice melting turns to?", options: ["Water", "Gas", "Solid", "Rock"], correctIndex: 0, hint: "Liquid.", explanation: "Water." },
        { q: "Water freezing turns to?", options: ["Ice", "Steam", "Air", "Juice"], correctIndex: 0, hint: "Solid.", explanation: "Ice." },
        { q: "Boiling water makes?", options: ["Steam", "Ice", "Snow", "Mud"], correctIndex: 0, hint: "Gas.", explanation: "Steam." },
        { q: "Hardest solid?", options: ["Diamond", "Chalk", "Paper", "Wood"], correctIndex: 0, hint: "Gem.", explanation: "Diamond." },
        { q: "Can you pour sand?", options: ["Yes", "No"], correctIndex: 0, hint: "Tiny solids.", explanation: "Yes." },
        { q: "Is honey a liquid?", options: ["Yes", "No"], correctIndex: 0, hint: "Thick.", explanation: "Yes." },
        { q: "Matter is?", options: ["Everything", "Nothing", "Just gas", "Just solid"], correctIndex: 0, hint: "Stuff.", explanation: "Everything." },
        { q: "Invisible matter?", options: ["Air", "Water", "Ice", "Wood"], correctIndex: 0, hint: "Gas.", explanation: "Air." },
        { q: "Reversible change?", options: ["Melting ice", "Burning wood", "Cooking egg", "Rusting"], correctIndex: 0, hint: "Go back.", explanation: "Melting ice." },
        { q: "Irreversible change?", options: ["Burning paper", "Freezing water", "Folding paper", "Mixing sand"], correctIndex: 0, hint: "Cant fix.", explanation: "Burning paper." },
        { q: "Which is heavy?", options: ["Brick", "Feather", "Air", "Leaf"], correctIndex: 0, hint: "Solid.", explanation: "Brick." }
    ],
    "302": [
        { q: "Strong material?", options: ["Metal", "Paper", "Cotton", "Glass"], correctIndex: 0, hint: "Hard.", explanation: "Metal." },
        { q: "Transparent material?", options: ["Glass", "Wood", "Metal", "Stone"], correctIndex: 0, hint: "See.", explanation: "Glass." },
        { q: "Flexible?", options: ["Rubber", "Glass", "Stone", "Brick"], correctIndex: 0, hint: "Bend.", explanation: "Rubber." },
        { q: "Absorbent?", options: ["Sponge", "Plastic", "Metal", "Glass"], correctIndex: 0, hint: "Soak.", explanation: "Sponge." },
        { q: "Waterproof?", options: ["Plastic", "Paper", "Tissue", "Bread"], correctIndex: 0, hint: "Dry.", explanation: "Plastic." },
        { q: "Building needs?", options: ["Strong base", "Weak base", "No base", "Sand base"], correctIndex: 0, hint: "Foundation.", explanation: "Strong base." },
        { q: "Bridge shape?", options: ["Arch", "Circle", "Square", "Line"], correctIndex: 0, hint: "Strong.", explanation: "Arch." },
        { q: "Concrete is?", options: ["Hard", "Soft", "Liquid", "Gas"], correctIndex: 0, hint: "Sidewalk.", explanation: "Hard." },
        { q: "Wood comes from?", options: ["Trees", "Ground", "Sky", "Water"], correctIndex: 0, hint: "Plant.", explanation: "Trees." },
        { q: "Plastic comes from?", options: ["Oil", "Trees", "Rocks", "Sand"], correctIndex: 0, hint: "Man-made.", explanation: "Oil." },
        { q: "Brick is made of?", options: ["Clay", "Wood", "Metal", "Plastic"], correctIndex: 0, hint: "Baked.", explanation: "Clay." },
        { q: "Glass comes from?", options: ["Sand", "Trees", "Oil", "Water"], correctIndex: 0, hint: "Heat.", explanation: "Sand." },
        { q: "Paper comes from?", options: ["Trees", "Sand", "Oil", "Rocks"], correctIndex: 0, hint: "Wood.", explanation: "Trees." },
        { q: "Steel is?", options: ["Metal", "Wood", "Plastic", "Fabric"], correctIndex: 0, hint: "Strong.", explanation: "Metal." },
        { q: "Wool comes from?", options: ["Sheep", "Trees", "Oil", "Ground"], correctIndex: 0, hint: "Animal.", explanation: "Sheep." }
    ],
    "303": [
        { q: "Fast change?", options: ["Volcano", "Erosion", "Weathering", "Rust"], correctIndex: 0, hint: "Boom.", explanation: "Volcano." },
        { q: "Slow change?", options: ["Erosion", "Earthquake", "Landslide", "Flood"], correctIndex: 0, hint: "Time.", explanation: "Erosion." },
        { q: "Wind causes?", options: ["Erosion", "Volcano", "Earthquake", "Magma"], correctIndex: 0, hint: "Blow.", explanation: "Erosion." },
        { q: "Water causes?", options: ["Canyons", "Volcanoes", "Mountains", "Stars"], correctIndex: 0, hint: "Cut.", explanation: "Canyons." },
        { q: "Earthquake is?", options: ["Shaking", "Wind", "Rain", "Fire"], correctIndex: 0, hint: "Move.", explanation: "Shaking." },
        { q: "Lava comes from?", options: ["Volcano", "Cloud", "River", "Ocean"], correctIndex: 0, hint: "Hot.", explanation: "Volcano." },
        { q: "Weathering?", options: ["Breaking rocks", "Making rocks", "Painting", "Cleaning"], correctIndex: 0, hint: "Crack.", explanation: "Breaking rocks." },
        { q: "Landslide?", options: ["Dirt falling", "Snow falling", "Rain", "Wind"], correctIndex: 0, hint: "Gravity.", explanation: "Dirt falling." },
        { q: "Flood?", options: ["Too much water", "No water", "Fire", "Wind"], correctIndex: 0, hint: "Wet.", explanation: "Too much water." },
        { q: "Drought?", options: ["No rain", "Too much rain", "Snow", "Wind"], correctIndex: 0, hint: "Dry.", explanation: "No rain." },
        { q: "Glacier?", options: ["Moving ice", "Standing water", "Hot rock", "Wind"], correctIndex: 0, hint: "Slow.", explanation: "Moving ice." },
        { q: "Tsunami?", options: ["Big wave", "Small ripple", "Rain", "Wind"], correctIndex: 0, hint: "Ocean.", explanation: "Big wave." },
        { q: "Magma vs Lava?", options: ["Inside vs Outside", "Same", "Cold vs Hot", "Liquid vs Solid"], correctIndex: 0, hint: "Location.", explanation: "Inside vs Outside." },
        { q: "Fossil?", options: ["Ancient remains", "New bone", "Living animal", "Plant now"], correctIndex: 0, hint: "Rock.", explanation: "Ancient remains." },
        { q: "Canyon?", options: ["Deep valley", "High mountain", "Flat plain", "Ocean"], correctIndex: 0, hint: "Cut.", explanation: "Deep valley." }
    ],
    "304": [
        { q: "Water cycle?", options: ["Rain/Cloud/Sun", "Car/Bus", "Eat/Sleep"], correctIndex: 0, hint: "Circle.", explanation: "Rain/Cloud/Sun." },
        { q: "Evaporation?", options: ["Liquid to Gas", "Gas to Liquid"], correctIndex: 0, hint: "Dry.", explanation: "Liquid to Gas." },
        { q: "Condensation?", options: ["Gas to Liquid", "Liquid to Gas"], correctIndex: 0, hint: "Cloud.", explanation: "Gas to Liquid." },
        { q: "Precipitation?", options: ["Rain/Snow", "Sun", "Wind"], correctIndex: 0, hint: "Fall.", explanation: "Rain/Snow." },
        { q: "Most water is?", options: ["Salt", "Fresh"], correctIndex: 0, hint: "Ocean.", explanation: "Salt." },
        { q: "Glacier?", options: ["Ice", "Water", "Steam", "Rock"], correctIndex: 0, hint: "Frozen.", explanation: "Ice." },
        { q: "Ocean water?", options: ["Salt", "Fresh", "Sweet", "Sour"], correctIndex: 0, hint: "Taste.", explanation: "Salt." },
        { q: "River water?", options: ["Fresh", "Salt", "Ice", "Gas"], correctIndex: 0, hint: "Drink.", explanation: "Fresh." },
        { q: "Cloud made of?", options: ["Water drops", "Cotton", "Smoke", "Fire"], correctIndex: 0, hint: "Vapor.", explanation: "Water drops." },
        { q: "Sun helps water cycle?", options: ["Yes", "No"], correctIndex: 0, hint: "Heat.", explanation: "Yes." },
        { q: "Groundwater?", options: ["Underground water", "River", "Ocean", "Rain"], correctIndex: 0, hint: "Well.", explanation: "Underground water." },
        { q: "Runoff?", options: ["Water flowing", "Water sitting", "Ice", "Steam"], correctIndex: 0, hint: "Move.", explanation: "Water flowing." },
        { q: "Transpiration?", options: ["Plants release water", "Animals drink", "Rain falling", "Ice melting"], correctIndex: 0, hint: "Leaves.", explanation: "Plants release water." },
        { q: "Is water vapor gas?", options: ["Yes", "No"], correctIndex: 0, hint: "Steam.", explanation: "Yes." },
        { q: "Hail?", options: ["Ice balls", "Rain", "Snow", "Fog"], correctIndex: 0, hint: "Hard.", explanation: "Ice balls." }
    ],
    "402": [
        { q: "Magnetic poles?", options: ["North/South", "East/West", "Up/Down", "Left/Right"], correctIndex: 0, hint: "N/S.", explanation: "North/South." },
        { q: "Opposites?", options: ["Attract", "Repel", "Nothing", "Sleep"], correctIndex: 0, hint: "Pull.", explanation: "Attract." },
        { q: "Likes?", options: ["Repel", "Attract", "Stick", "Pull"], correctIndex: 0, hint: "Push away.", explanation: "Repel." },
        { q: "Magnet metal?", options: ["Iron", "Gold", "Silver", "Aluminum"], correctIndex: 0, hint: "Fe.", explanation: "Iron." },
        { q: "Earth is a magnet?", options: ["Yes", "No"], correctIndex: 0, hint: "Compass.", explanation: "Yes." },
        { q: "Compass points?", options: ["North", "South", "East", "West"], correctIndex: 0, hint: "N.", explanation: "North." },
        { q: "Invisible force?", options: ["Magnetism", "Glue", "Tape", "Rope"], correctIndex: 0, hint: "Field.", explanation: "Magnetism." },
        { q: "Magnet shape?", options: ["Horseshoe", "Triangle", "Star", "Liquid"], correctIndex: 0, hint: "U shape.", explanation: "Horseshoe." },
        { q: "Is plastic magnetic?", options: ["No", "Yes"], correctIndex: 0, hint: "Not metal.", explanation: "No." },
        { q: "Lodestone?", options: ["Natural magnet", "Fake", "Plastic", "Wood"], correctIndex: 0, hint: "Rock.", explanation: "Natural magnet." },
        { q: "Electromagnet?", options: ["Uses electricity", "Permanent", "Stone", "Plastic"], correctIndex: 0, hint: "Wire.", explanation: "Uses electricity." },
        { q: "Field lines?", options: ["Show force", "Show color", "Show heat", "Show sound"], correctIndex: 0, hint: "Invisible.", explanation: "Show force." },
        { q: "Compass needle?", options: ["Tiny magnet", "Plastic", "Wood", "Glass"], correctIndex: 0, hint: "Points.", explanation: "Tiny magnet." },
        { q: "Repel means?", options: ["Push away", "Pull together", "Stick", "Break"], correctIndex: 0, hint: "Away.", explanation: "Push away." },
        { q: "Attract means?", options: ["Pull together", "Push away", "Break", "Fall"], correctIndex: 0, hint: "Closer.", explanation: "Pull together." }
    ],
    "401": [
        { q: "Force?", options: ["Push/Pull", "Sleep", "Eat", "Think"], correctIndex: 0, hint: "Move.", explanation: "Push/Pull." },
        { q: "Gravity?", options: ["Pull down", "Push up", "Side", "Spin"], correctIndex: 0, hint: "Fall.", explanation: "Pull down." },
        { q: "Friction?", options: ["Rubbing", "Falling", "Floating", "Flying"], correctIndex: 0, hint: "Stop.", explanation: "Rubbing." },
        { q: "Balanced force?", options: ["No motion", "Motion", "Fast", "Slow"], correctIndex: 0, hint: "Still.", explanation: "No motion." },
        { q: "Speed?", options: ["Fast/Slow", "Heavy/Light"], correctIndex: 0, hint: "Rate.", explanation: "Fast/Slow." },
        { q: "Unbalanced force?", options: ["Motion", "No motion", "Still", "Stop"], correctIndex: 0, hint: "Move.", explanation: "Motion." },
        { q: "Push moves?", options: ["Away", "Closer", "Up", "Down"], correctIndex: 0, hint: "Go.", explanation: "Away." },
        { q: "Pull moves?", options: ["Closer", "Away", "Up", "Down"], correctIndex: 0, hint: "Come.", explanation: "Closer." },
        { q: "Weight?", options: ["Gravity pull", "Size", "Color", "Shape"], correctIndex: 0, hint: "Heavy.", explanation: "Gravity pull." },
        { q: "Magnet force?", options: ["Attract/Repel", "Push/Pull only", "None", "Heat"], correctIndex: 0, hint: "Field.", explanation: "Attract/Repel." },
        { q: "Mass?", options: ["Amount of matter", "Weight", "Size", "Shape"], correctIndex: 0, hint: "Stuff.", explanation: "Amount of matter." },
        { q: "Motion?", options: ["Change position", "Stay still", "Sleep", "Grow"], correctIndex: 0, hint: "Move.", explanation: "Change position." },
        { q: "Velocity?", options: ["Speed + Direction", "Speed only", "Direction only", "Weight"], correctIndex: 0, hint: "Vector.", explanation: "Speed + Direction." },
        { q: "Acceleration?", options: ["Speed up", "Stay same", "Stop", "Turn"], correctIndex: 0, hint: "Faster.", explanation: "Speed up." },
        { q: "Newton?", options: ["Force unit", "Cookie", "Town", "Car"], correctIndex: 0, hint: "Measure.", explanation: "Force unit." }
    ],
    "403": [
        { q: "Butterfly life?", options: ["Egg, Larva, Pupa, Adult", "Born adult"], correctIndex: 0, hint: "Change.", explanation: "Egg, Larva, Pupa, Adult." },
        { q: "Frog life?", options: ["Egg, Tadpole, Frog", "Egg, Chicken"], correctIndex: 0, hint: "Water.", explanation: "Egg, Tadpole, Frog." },
        { q: "Plant life?", options: ["Seed, Sprout, Plant", "Rock"], correctIndex: 0, hint: "Grow.", explanation: "Seed, Sprout, Plant." },
        { q: "Metamorphosis?", options: ["Change form", "Stay same"], correctIndex: 0, hint: "Transform.", explanation: "Change form." },
        { q: "Larva is?", options: ["Caterpillar", "Butterfly"], correctIndex: 0, hint: "Eat.", explanation: "Caterpillar." },
        { q: "Pupa is?", options: ["Cocoon", "Egg", "Adult", "Seed"], correctIndex: 0, hint: "Rest.", explanation: "Cocoon." },
        { q: "Adult lays?", options: ["Eggs", "Seeds", "Rocks", "Milk"], correctIndex: 0, hint: "Baby.", explanation: "Eggs." },
        { q: "Germination?", options: ["Seed sprouting", "Leaf falling", "Flower dying", "Root rotting"], correctIndex: 0, hint: "Start.", explanation: "Seed sprouting." },
        { q: "Lifecycle?", options: ["Circle of life", "Line of life", "Square of life", "Triangle of life"], correctIndex: 0, hint: "Repeat.", explanation: "Circle of life." },
        { q: "Tadpole has?", options: ["Tail", "Legs", "Wings", "Fur"], correctIndex: 0, hint: "Swim.", explanation: "Tail." },
        { q: "Chrysalis?", options: ["Butterfly pupa", "Moth pupa", "Egg", "Larva"], correctIndex: 0, hint: "Hard shell.", explanation: "Butterfly pupa." },
        { q: "Cocoon?", options: ["Moth pupa", "Butterfly pupa", "Egg", "Larva"], correctIndex: 0, hint: "Silk.", explanation: "Moth pupa." },
        { q: "Nymph?", options: ["Small adult", "Larva", "Egg", "Pupa"], correctIndex: 0, hint: "Insect.", explanation: "Small adult." },
        { q: "Mammal birth?", options: ["Live young", "Eggs", "Seeds", "Spores"], correctIndex: 0, hint: "Baby.", explanation: "Live young." },
        { q: "Bird birth?", options: ["Eggs", "Live young", "Seeds", "Spores"], correctIndex: 0, hint: "Shell.", explanation: "Eggs." }
    ],
    "404": [
        { q: "Inherited?", options: ["Eye color", "Reading", "Bike riding"], correctIndex: 0, hint: "Born.", explanation: "Eye color." },
        { q: "Learned?", options: ["Math", "Hair color", "Height"], correctIndex: 0, hint: "School.", explanation: "Math." },
        { q: "Instinct?", options: ["Spider web", "Cooking", "Driving"], correctIndex: 0, hint: "Know.", explanation: "Spider web." },
        { q: "Environment?", options: ["Surroundings", "Genes"], correctIndex: 0, hint: "Outside.", explanation: "Surroundings." },
        { q: "Trait?", options: ["Feature", "Toy"], correctIndex: 0, hint: "Look.", explanation: "Feature." },
        { q: "Hair color?", options: ["Inherited", "Learned", "Environment", "Instinct"], correctIndex: 0, hint: "Genes.", explanation: "Inherited." },
        { q: "Scar?", options: ["Environment", "Inherited", "Learned", "Instinct"], correctIndex: 0, hint: "Hurt.", explanation: "Environment." },
        { q: "Bird migration?", options: ["Instinct", "Learned", "Inherited", "Environment"], correctIndex: 0, hint: "Fly south.", explanation: "Instinct." },
        { q: "Reading?", options: ["Learned", "Inherited", "Instinct", "Environment"], correctIndex: 0, hint: "Study.", explanation: "Learned." },
        { q: "Height?", options: ["Inherited/Env", "Learned", "Instinct", "Magic"], correctIndex: 0, hint: "Genes+Food.", explanation: "Inherited/Env." },
        { q: "Offspring?", options: ["Children", "Parents", "Grandparents", "Cousins"], correctIndex: 0, hint: "Baby.", explanation: "Children." },
        { q: "Parent?", options: ["Mother/Father", "Child", "Baby", "Egg"], correctIndex: 0, hint: "Adult.", explanation: "Mother/Father." },
        { q: "Gene?", options: ["DNA instruction", "Pants", "Shoe", "Hat"], correctIndex: 0, hint: "Cell.", explanation: "DNA instruction." },
        { q: "Variation?", options: ["Difference", "Same", "Copy", "Clone"], correctIndex: 0, hint: "Variety.", explanation: "Difference." },
        { q: "Adaptation?", options: ["Help survive", "Hurt", "Kill", "End"], correctIndex: 0, hint: "Fit.", explanation: "Help survive." }
    ],
    "504": [
        { q: "Tsunami?", options: ["Giant wave", "Fire", "Wind", "Rain"], correctIndex: 0, hint: "Ocean.", explanation: "Giant wave." },
        { q: "Volcano releases?", options: ["Lava", "Ice", "Water", "Sand"], correctIndex: 0, hint: "Hot.", explanation: "Lava." },
        { q: "Hurricane is?", options: ["Storm", "Fire", "Shake", "Snow"], correctIndex: 0, hint: "Wind/Rain.", explanation: "Storm." },
        { q: "Tornado shape?", options: ["Funnel", "Square", "Circle", "Line"], correctIndex: 0, hint: "Twister.", explanation: "Funnel." },
        { q: "Flood?", options: ["Too much water", "No water", "Fire", "Wind"], correctIndex: 0, hint: "Overflow.", explanation: "Too much water." },
        { q: "Drought?", options: ["No rain", "Too much rain", "Snow", "Wind"], correctIndex: 0, hint: "Dry.", explanation: "No rain." },
        { q: "Earthquake?", options: ["Ground shake", "Wind", "Rain", "Fire"], correctIndex: 0, hint: "Move.", explanation: "Ground shake." },
        { q: "Magma vs Lava?", options: ["Inside vs Outside", "Same", "Cold vs Hot", "Liquid vs Solid"], correctIndex: 0, hint: "Location.", explanation: "Inside vs Outside." },
        { q: "Fault line?", options: ["Crack in Earth", "Road", "River", "Wall"], correctIndex: 0, hint: "Quake.", explanation: "Crack in Earth." },
        { q: "Blizzard?", options: ["Snow storm", "Rain storm", "Sand storm", "Fire"], correctIndex: 0, hint: "Cold.", explanation: "Snow storm." },
        { q: "Avalanche?", options: ["Falling snow", "Falling rock", "Rain", "Wind"], correctIndex: 0, hint: "Mountain.", explanation: "Falling snow." },
        { q: "Wildfire cause?", options: ["Lightning", "Rain", "Snow", "Ice"], correctIndex: 0, hint: "Spark.", explanation: "Lightning." },
        { q: "Safety in quake?", options: ["Drop, Cover, Hold", "Run", "Jump", "Swim"], correctIndex: 0, hint: "Table.", explanation: "Drop, Cover, Hold." },
        { q: "Eye of hurricane?", options: ["Calm center", "Windy part", "Rainy part", "Outside"], correctIndex: 0, hint: "Middle.", explanation: "Calm center." },
        { q: "Landslide?", options: ["Falling dirt", "Water", "Snow", "Air"], correctIndex: 0, hint: "Gravity.", explanation: "Falling dirt." }
    ],
    "501": [
        { q: "Energy source?", options: ["Sun", "Rock", "Sand", "Moon"], correctIndex: 0, hint: "Light.", explanation: "Sun." },
        { q: "Sound travels?", options: ["Waves", "Lines", "Circles", "Squares"], correctIndex: 0, hint: "Vibrate.", explanation: "Waves." },
        { q: "Light travels?", options: ["Straight line", "Curved", "Zigzag", "Circle"], correctIndex: 0, hint: "Beam.", explanation: "Straight line." },
        { q: "Heat flows?", options: ["Hot to Cold", "Cold to Hot"], correctIndex: 0, hint: "Warm.", explanation: "Hot to Cold." },
        { q: "Conductor?", options: ["Metal", "Plastic", "Wood", "Rubber"], correctIndex: 0, hint: "Wire.", explanation: "Metal." },
        { q: "Insulator?", options: ["Rubber", "Metal", "Water", "Copper"], correctIndex: 0, hint: "Stop.", explanation: "Rubber." },
        { q: "Potential energy?", options: ["Stored", "Moving", "Light", "Sound"], correctIndex: 0, hint: "Wait.", explanation: "Stored." },
        { q: "Kinetic energy?", options: ["Moving", "Stored", "Chemical", "Potential"], correctIndex: 0, hint: "Go.", explanation: "Moving." },
        { q: "Chemical energy?", options: ["Food/Battery", "Light", "Sound", "Heat"], correctIndex: 0, hint: "Store.", explanation: "Food/Battery." },
        { q: "Solar energy?", options: ["From Sun", "From Wind", "From Water", "From Earth"], correctIndex: 0, hint: "Star.", explanation: "From Sun." },
        { q: "Electrical energy?", options: ["Moving electrons", "Moving atoms", "Moving molecules", "Moving neutrons"], correctIndex: 0, hint: "Wire.", explanation: "Moving electrons." },
        { q: "Mechanical energy?", options: ["Motion", "Heat", "Light", "Sound"], correctIndex: 0, hint: "Move.", explanation: "Motion." },
        { q: "Thermal energy?", options: ["Heat", "Cold", "Light", "Sound"], correctIndex: 0, hint: "Hot.", explanation: "Heat." },
        { q: "Circuit?", options: ["Path for electricity", "Circle shape", "Race track", "Map"], correctIndex: 0, hint: "Loop.", explanation: "Path for electricity." },
        { q: "Switch?", options: ["Opens/closes circuit", "Turns", "Spins", "Falls"], correctIndex: 0, hint: "On/Off.", explanation: "Opens/closes circuit." }
    ],
    "502": [
        { q: "Collision?", options: ["Hit", "Miss"], correctIndex: 0, hint: "Bang.", explanation: "Hit." },
        { q: "Transfer?", options: ["Move", "Stop"], correctIndex: 0, hint: "Go.", explanation: "Move." },
        { q: "Stored energy?", options: ["Potential", "Kinetic"], correctIndex: 0, hint: "Wait.", explanation: "Potential." },
        { q: "Moving energy?", options: ["Kinetic", "Potential"], correctIndex: 0, hint: "Go.", explanation: "Kinetic." },
        { q: "Battery?", options: ["Chemical", "Solar"], correctIndex: 0, hint: "Store.", explanation: "Chemical." },
        { q: "Conservation of Energy?", options: ["Not lost", "Lost", "Created", "Destroyed"], correctIndex: 0, hint: "Save.", explanation: "Not lost." },
        { q: "Energy conversion?", options: ["Change form", "Stay same", "Disappear", "Grow"], correctIndex: 0, hint: "Switch.", explanation: "Change form." },
        { q: "Sound needs?", options: ["Medium", "Nothing", "Vacuum", "Space"], correctIndex: 0, hint: "Air.", explanation: "Medium." },
        { q: "Light speed?", options: ["Fastest", "Slowest", "Medium", "Stopped"], correctIndex: 0, hint: "Zoom.", explanation: "Fastest." },
        { q: "Heat source?", options: ["Sun", "Ice", "Water", "Wind"], correctIndex: 0, hint: "Warm.", explanation: "Sun." },
        { q: "Friction makes?", options: ["Heat", "Cold", "Light", "Sound"], correctIndex: 0, hint: "Rub.", explanation: "Heat." },
        { q: "Gravity is?", options: ["Force", "Energy", "Matter", "Gas"], correctIndex: 0, hint: "Pull.", explanation: "Force." },
        { q: "Work?", options: ["Force x Distance", "Sleep", "Eat", "Play"], correctIndex: 0, hint: "Move.", explanation: "Force x Distance." },
        { q: "Simple machine?", options: ["Lever", "Computer", "Robot", "Phone"], correctIndex: 0, hint: "Tool.", explanation: "Lever." },
        { q: "Photosynthesis?", options: ["Light to Chemical", "Heat to Light", "Sound to Heat", "Chemical to Motion"], correctIndex: 0, hint: "Plant.", explanation: "Light to Chemical." }
    ],
    "503": [
        { q: "Fossil?", options: ["Old remains", "New bone"], correctIndex: 0, hint: "Rock.", explanation: "Old remains." },
        { q: "Sedimentary?", options: ["Layers", "Fire"], correctIndex: 0, hint: "Stack.", explanation: "Layers." },
        { q: "Igneous?", options: ["Fire/Lava", "Water"], correctIndex: 0, hint: "Hot.", explanation: "Fire/Lava." },
        { q: "Metamorphic?", options: ["Change", "Stay"], correctIndex: 0, hint: "Pressure.", explanation: "Change." },
        { q: "Geologist?", options: ["Rock scientist", "Star scientist"], correctIndex: 0, hint: "Earth.", explanation: "Rock scientist." },
        { q: "Mineral?", options: ["Building block", "Plant", "Animal", "Gas"], correctIndex: 0, hint: "Gem.", explanation: "Building block." },
        { q: "Rock cycle?", options: ["Change form", "Stay same", "Disappear", "Melt only"], correctIndex: 0, hint: "Circle.", explanation: "Change form." },
        { q: "Magma?", options: ["Underground lava", "Rock", "Water", "Air"], correctIndex: 0, hint: "Hot.", explanation: "Underground lava." },
        { q: "Erosion?", options: ["Wear away", "Build up", "Stay", "Grow"], correctIndex: 0, hint: "Wind/Water.", explanation: "Wear away." },
        { q: "Deposition?", options: ["Drop off", "Pick up", "Wear away", "Break"], correctIndex: 0, hint: "Pile.", explanation: "Drop off." },
        { q: "Hardness scale?", options: ["Mohs", "Richter", "Fahrenheit", "Gram"], correctIndex: 0, hint: "Scratch.", explanation: "Mohs." },
        { q: "Diamond?", options: ["Hardest mineral", "Softest", "Liquid", "Gas"], correctIndex: 0, hint: "Gem.", explanation: "Hardest mineral." },
        { q: "Talc?", options: ["Softest mineral", "Hardest", "Liquid", "Gas"], correctIndex: 0, hint: "Powder.", explanation: "Softest mineral." },
        { q: "Soil?", options: ["Dirt/Organic", "Rock only", "Water only", "Air"], correctIndex: 0, hint: "Grow.", explanation: "Dirt/Organic." },
        { q: "Humus?", options: ["Decayed matter", "Rock", "Sand", "Clay"], correctIndex: 0, hint: "Soil.", explanation: "Decayed matter." }
    ],
    "603": [
        { q: "Planet we live on?", options: ["Earth", "Mars", "Venus", "Moon"], correctIndex: 0, hint: "Home.", explanation: "Earth." },
        { q: "Red Planet?", options: ["Mars", "Jupiter", "Saturn", "Sun"], correctIndex: 0, hint: "Rust.", explanation: "Mars." },
        { q: "Planet with rings?", options: ["Saturn", "Mercury", "Venus", "Mars"], correctIndex: 0, hint: "Beautiful.", explanation: "Saturn." },
        { q: "Closest to Sun?", options: ["Mercury", "Earth", "Pluto", "Neptune"], correctIndex: 0, hint: "Hot.", explanation: "Mercury." },
        { q: "Farthest planet?", options: ["Neptune", "Mercury", "Mars", "Venus"], correctIndex: 0, hint: "Cold.", explanation: "Neptune." },
        { q: "Largest Planet?", options: ["Jupiter", "Mars", "Earth", "Venus"], correctIndex: 0, hint: "Big.", explanation: "Jupiter." },
        { q: "Sun is a?", options: ["Star", "Planet", "Moon", "Comet"], correctIndex: 0, hint: "Hot.", explanation: "Star." },
        { q: "Earth orbits?", options: ["Sun", "Moon", "Mars", "Stars"], correctIndex: 0, hint: "Year.", explanation: "Sun." },
        { q: "Moon orbits?", options: ["Earth", "Sun", "Mars", "Venus"], correctIndex: 0, hint: "Month.", explanation: "Earth." },
        { q: "Gravity?", options: ["Pull", "Push", "Float", "Fly"], correctIndex: 0, hint: "Down.", explanation: "Pull." },
        { q: "Asteroid belt?", options: ["Between Mars/Jupiter", "Near Sun", "Outside Pluto", "Near Earth"], correctIndex: 0, hint: "Rocks.", explanation: "Between Mars/Jupiter." },
        { q: "Comet?", options: ["Ice/Dust ball", "Rock", "Star", "Planet"], correctIndex: 0, hint: "Tail.", explanation: "Ice/Dust ball." },
        { q: "Dwarf Planet?", options: ["Pluto", "Earth", "Sun", "Jupiter"], correctIndex: 0, hint: "Small.", explanation: "Pluto." },
        { q: "Gas Giants?", options: ["Jup/Sat/Ura/Nep", "Mer/Ven/Ear/Mar"], correctIndex: 0, hint: "Big.", explanation: "Jup/Sat/Ura/Nep." },
        { q: "Terrestrial Planets?", options: ["Mer/Ven/Ear/Mar", "Jup/Sat/Ura/Nep"], correctIndex: 0, hint: "Rock.", explanation: "Mer/Ven/Ear/Mar." }
    ],
    "601": [
        { q: "Atom?", options: ["Smallest unit", "Big rock"], correctIndex: 0, hint: "Tiny.", explanation: "Smallest unit." },
        { q: "Matter?", options: ["Stuff", "Nothing"], correctIndex: 0, hint: "Space.", explanation: "Stuff." },
        { q: "Solid particles?", options: ["Tight", "Loose"], correctIndex: 0, hint: "Close.", explanation: "Tight." },
        { q: "Gas particles?", options: ["Loose", "Tight"], correctIndex: 0, hint: "Fly.", explanation: "Loose." },
        { q: "Element?", options: ["Pure substance", "Mix"], correctIndex: 0, hint: "One.", explanation: "Pure substance." },
        { q: "Molecule?", options: ["Group of atoms", "Single atom", "Big rock", "Liquid"], correctIndex: 0, hint: "Bond.", explanation: "Group of atoms." },
        { q: "Liquid particles?", options: ["Flow", "Fixed", "Fly", "Stop"], correctIndex: 0, hint: "Move.", explanation: "Flow." },
        { q: "Mass?", options: ["Amount of matter", "Weight", "Size", "Shape"], correctIndex: 0, hint: "Stuff.", explanation: "Amount of matter." },
        { q: "Volume?", options: ["Space taken up", "Loudness", "Weight", "Mass"], correctIndex: 0, hint: "Size.", explanation: "Space taken up." },
        { q: "Density?", options: ["Mass/Volume", "Weight", "Size", "Shape"], correctIndex: 0, hint: "Float.", explanation: "Mass/Volume." },
        { q: "Proton?", options: ["Positive", "Negative", "Neutral", "None"], correctIndex: 0, hint: "+", explanation: "Positive." },
        { q: "Electron?", options: ["Negative", "Positive", "Neutral", "None"], correctIndex: 0, hint: "-", explanation: "Negative." },
        { q: "Neutron?", options: ["Neutral", "Positive", "Negative", "None"], correctIndex: 0, hint: "0", explanation: "Neutral." },
        { q: "Nucleus?", options: ["Center of atom", "Outside", "Electron", "Bond"], correctIndex: 0, hint: "Core.", explanation: "Center of atom." },
        { q: "Periodic Table?", options: ["Chart of elements", "Map", "Book", "Graph"], correctIndex: 0, hint: "List.", explanation: "Chart of elements." }
    ],
    "602": [
        { q: "Chemical change?", options: ["New substance", "Same substance"], correctIndex: 0, hint: "New.", explanation: "New substance." },
        { q: "Physical change?", options: ["Same substance", "New substance"], correctIndex: 0, hint: "Same", explanation: "Same substance." },
        { q: "Reaction?", options: ["Change happens", "Nothing"], correctIndex: 0, hint: "Act", explanation: "Change happens." },
        { q: "Mixture?", options: ["Salad", "Water"], correctIndex: 0, hint: "Mix.", explanation: "Salad." },
        { q: "Solution?", options: ["Salt water", "Sand water"], correctIndex: 0, hint: "Dissolve.", explanation: "Salt water." },
        { q: "Burn wood?", options: ["Chemical", "Physical"], correctIndex: 0, hint: "Ash.", explanation: "Chemical." },
        { q: "Melt ice?", options: ["Physical", "Chemical"], correctIndex: 0, hint: "Water.", explanation: "Physical." },
        { q: "Bake cake?", options: ["Chemical", "Physical"], correctIndex: 0, hint: "New.", explanation: "Chemical." },
        { q: "Rip paper?", options: ["Physical", "Chemical"], correctIndex: 0, hint: "Same.", explanation: "Physical." },
        { q: "Rust?", options: ["Chemical", "Physical"], correctIndex: 0, hint: "Oxidation.", explanation: "Chemical." },
        { q: "Fizzing?", options: ["Sign of chemical", "Physical"], correctIndex: 0, hint: "Gas.", explanation: "Sign of chemical." },
        { q: "Color change?", options: ["Sign of chemical", "Physical"], correctIndex: 0, hint: "New look.", explanation: "Sign of chemical." },
        { q: "Heat release?", options: ["Sign of chemical", "Physical"], correctIndex: 0, hint: "Hot.", explanation: "Sign of chemical." },
        { q: "Precipitate?", options: ["Solid forms", "Gas forms", "Liquid forms", "Nothing"], correctIndex: 0, hint: "Chunk.", explanation: "Solid forms." },
        { q: "Evaporation?", options: ["Physical", "Chemical"], correctIndex: 0, hint: "State change.", explanation: "Physical." }
    ],
    "604": [
        { q: "Gravity?", options: ["Pull", "Push"], correctIndex: 0, hint: "Down.", explanation: "Pull." },
        { q: "Star?", options: ["Gas", "Rock"], correctIndex: 0, hint: "Burn.", explanation: "Gas." },
        { q: "Sun?", options: ["Star", "Planet"], correctIndex: 0, hint: "Center.", explanation: "Star." },
        { q: "Orbit?", options: ["Circle path", "Straight"], correctIndex: 0, hint: "Around.", explanation: "Circle path." },
        { q: "Universe?", options: ["All", "Earth"], correctIndex: 0, hint: "Big.", explanation: "All." },
        { q: "Black Hole?", options: ["Strong gravity", "Empty space", "Star", "Planet"], correctIndex: 0, hint: "Pull.", explanation: "Strong gravity." },
        { q: "Galaxy?", options: ["Group of stars", "One star", "Planet", "Moon"], correctIndex: 0, hint: "Milky Way.", explanation: "Group of stars." },
        { q: "Light Year?", options: ["Distance", "Time", "Speed", "Weight"], correctIndex: 0, hint: "Far.", explanation: "Distance." },
        { q: "Constellation?", options: ["Star picture", "Planet", "Moon", "Sun"], correctIndex: 0, hint: "Shape.", explanation: "Star picture." },
        { q: "Telescope?", options: ["See far", "See small", "Hear", "Smell"], correctIndex: 0, hint: "Look.", explanation: "See far." },
        { q: "Supernova?", options: ["Exploding star", "New star", "Planet", "Comet"], correctIndex: 0, hint: "Boom.", explanation: "Exploding star." },
        { q: "Nebula?", options: ["Gas cloud", "Rock", "Star", "Planet"], correctIndex: 0, hint: "Birth.", explanation: "Gas cloud." },
        { q: "Big Bang?", options: ["Start of universe", "End", "Middle", "Sound"], correctIndex: 0, hint: "Begin.", explanation: "Start of universe." },
        { q: "Milky Way?", options: ["Our galaxy", "Candy", "Star", "Planet"], correctIndex: 0, hint: "Home.", explanation: "Our galaxy." },
        { q: "Meteor?", options: ["Rock in atmosphere", "Star", "Planet", "Moon"], correctIndex: 0, hint: "Streak.", explanation: "Rock in atmosphere." }
    ]
};

export const SCIENCE_ASSESS: Record<string, QuestionTemplate[]> = {};

const allIds = [
    ...Array.from({length: 4}, (_,i)=>101+i),
    ...Array.from({length: 4}, (_,i)=>201+i),
    ...Array.from({length: 4}, (_,i)=>301+i),
    ...Array.from({length: 4}, (_,i)=>401+i),
    ...Array.from({length: 4}, (_,i)=>501+i),
    ...Array.from({length: 4}, (_,i)=>601+i)
];

const generateQuizSet = (id: string, startIdx: number = 0): QuestionTemplate[] => {
    return Array.from({length: 15}, (_, i) => ({
        q: `Science Quiz Q${startIdx + i + 1} (Lesson ${id}): Select the scientific principle.`,
        options: ["Proven Theory", "Opinion", "Magic", "None"],
        correctIndex: 0,
        explanation: "Based on the scientific method."
    }));
};

allIds.forEach(id => {
    const key = id.toString();
    const realQuestions = REAL_ASSESS[key] || [];

    if (realQuestions.length >= 15) {
        SCIENCE_ASSESS[key] = realQuestions.slice(0, 15);
    } else {
        const needed = 15 - realQuestions.length;
        const generated = generateQuizSet(key, realQuestions.length).slice(0, needed);
        SCIENCE_ASSESS[key] = [...realQuestions, ...generated];
    }
});

SCIENCE_ASSESS['default'] = generateQuizSet('General');